// <auto-generated />
using System;
using HdiBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HdiBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HdiBackend.Models.Office", b =>
                {
                    b.Property<int>("IdOffice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_office");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdOffice"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.HasKey("IdOffice");

                    b.ToTable("office");

                    b.HasData(
                        new
                        {
                            IdOffice = 1,
                            Address = "Oficina Central León"
                        });
                });

            modelBuilder.Entity("HdiBackend.Models.Policy", b =>
                {
                    b.Property<int>("IdOffice")
                        .HasColumnType("integer")
                        .HasColumnName("id_office");

                    b.Property<string>("PolicyNumber")
                        .HasColumnType("text")
                        .HasColumnName("policy_number");

                    b.Property<string>("Beneficiary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("beneficiary");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean")
                        .HasColumnName("is_paid");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issue_date");

                    b.Property<string>("LineOfBusiness")
                        .HasColumnType("text")
                        .HasColumnName("line_of_business");

                    b.Property<string>("PaymentFrequency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payment_frequency");

                    b.Property<string>("PolicyHolder")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("policy_holder");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("VehicleInfo")
                        .HasColumnType("text")
                        .HasColumnName("vehicle_info");

                    b.HasKey("IdOffice", "PolicyNumber");

                    b.ToTable("policy");
                });

            modelBuilder.Entity("HdiBackend.Models.Report", b =>
                {
                    b.Property<int>("IdReport")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_report");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdReport"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_time");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<int>("IdOffice")
                        .HasColumnType("integer")
                        .HasColumnName("id_office");

                    b.Property<int>("IdUser")
                        .HasColumnType("integer")
                        .HasColumnName("id_user");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("license_plate");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("policy_number");

                    b.Property<string>("ReporterName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reporter_name");

                    b.Property<string>("ReporterPhone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reporter_phone");

                    b.HasKey("IdReport");

                    b.HasIndex("IdUser");

                    b.HasIndex("IdOffice", "PolicyNumber");

                    b.ToTable("report");
                });

            modelBuilder.Entity("HdiBackend.Models.TypeUser", b =>
                {
                    b.Property<int>("IdType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_type");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdType"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("IdType");

                    b.ToTable("type_user");

                    b.HasData(
                        new
                        {
                            IdType = 1,
                            Type = "Admin"
                        },
                        new
                        {
                            IdType = 2,
                            Type = "Ajustador"
                        });
                });

            modelBuilder.Entity("HdiBackend.Models.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_user");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUser"));

                    b.Property<int>("IdType")
                        .HasColumnType("integer")
                        .HasColumnName("id_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Tel")
                        .HasColumnType("text")
                        .HasColumnName("tel");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("IdUser");

                    b.HasIndex("IdType");

                    b.ToTable("user");

                    b.HasData(
                        new
                        {
                            IdUser = 1,
                            IdType = 1,
                            Name = "admin",
                            Password = "$2a$11$nV7h3Iu4Hc5/QAoJo/nr7O45cuGkkiuJe9iiOUJdJVeymtU8IrOa2",
                            Tel = "6632223344",
                            Username = "admin"
                        },
                        new
                        {
                            IdUser = 2,
                            IdType = 2,
                            Name = "Paco el Chato",
                            Password = "$2a$11$LJHHuhlJzv.H.KUhhybB3OkeP6aOv6K3av3j0NpuGUsS2q54AwSre",
                            Username = "paco"
                        });
                });

            modelBuilder.Entity("HdiBackend.Models.Policy", b =>
                {
                    b.HasOne("HdiBackend.Models.Office", "Office")
                        .WithMany("Policies")
                        .HasForeignKey("IdOffice")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Office");
                });

            modelBuilder.Entity("HdiBackend.Models.Report", b =>
                {
                    b.HasOne("HdiBackend.Models.User", "Adjuster")
                        .WithMany("Reports")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HdiBackend.Models.Policy", "Policy")
                        .WithMany("Reports")
                        .HasForeignKey("IdOffice", "PolicyNumber")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Adjuster");

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("HdiBackend.Models.User", b =>
                {
                    b.HasOne("HdiBackend.Models.TypeUser", "TypeUser")
                        .WithMany("Users")
                        .HasForeignKey("IdType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypeUser");
                });

            modelBuilder.Entity("HdiBackend.Models.Office", b =>
                {
                    b.Navigation("Policies");
                });

            modelBuilder.Entity("HdiBackend.Models.Policy", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("HdiBackend.Models.TypeUser", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("HdiBackend.Models.User", b =>
                {
                    b.Navigation("Reports");
                });
#pragma warning restore 612, 618
        }
    }
}
